// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBD0IUxa8Py3v4bynNrACd40lXx_gFSavE',
    appId: '1:1033035198519:web:4906efa4b2262184264fb2',
    messagingSenderId: '1033035198519',
    projectId: 'alumni-app-18a42',
    authDomain: 'alumni-app-18a42.firebaseapp.com',
    storageBucket: 'alumni-app-18a42.appspot.com',
    measurementId: 'G-BZJNNFDVFK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALMpQ5tXYuvH1kOyhBNsB39if-Ttwf198',
    appId: '1:1033035198519:android:6ed9d4bb6cd8f15d264fb2',
    messagingSenderId: '1033035198519',
    projectId: 'alumni-app-18a42',
    storageBucket: 'alumni-app-18a42.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlo8w47S7RY0ZNPLQqy-0cggtT80ts0iM',
    appId: '1:1033035198519:ios:ce84194466df9311264fb2',
    messagingSenderId: '1033035198519',
    projectId: 'alumni-app-18a42',
    storageBucket: 'alumni-app-18a42.appspot.com',
    iosBundleId: 'com.example.alumniApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlo8w47S7RY0ZNPLQqy-0cggtT80ts0iM',
    appId: '1:1033035198519:ios:f00a5b5b06d8a169264fb2',
    messagingSenderId: '1033035198519',
    projectId: 'alumni-app-18a42',
    storageBucket: 'alumni-app-18a42.appspot.com',
    iosBundleId: 'com.example.alumniApp.RunnerTests',
  );
}
